-- ======================================================================================================
-- GOLD LAYER(business insights)
-- ======================================================================================================

create table gold_sales_fact as
select 
   o.order_id,
   o.customer_id,
   o.order_status,
   o.purchase_date,
   o.delivery_date,
   oi.order_item_id,
   oi.product_id,
   oi.seller_id,
   oi.price,
   oi.freight_value,
   p.product_catrgory_name,
   datediff(o.delivery_date,o.purchase_date) as delivery_days,
   (oi.price + oi.freight_value) as total_order_value
   from orders_cleansed o
   join order_items_cleansed oi on o.order_id = oi.order_id
   join products_cleansed p on oi.product_id = p.product_id;



select round(sum(total_order_value),2) as total_revenue  -- total revenue generated.
from gold_sales_fact;

select count(distinct order_id) as total_orders  -- total orders.
from gold_sales_fact;

select round(avg(total_order_value),2) as avg_order_value  -- average order value.
from gold_sales_fact;

select round(avg(delivery_days),2) as avg_delivery_days  -- average delivery days.
from gold_sales_fact
where delivery_days is not null;

select                                        -- Top 10 product category by revenue.
     product_catrgory_name,
     round(sum(total_order_value),2) as revenue
from gold_sales_fact
group by product_catrgory_name
order by revenue desc
limit 10;

select                                        -- Top 10 products by units sold.
    product_id,
    count(*) as total_units_sold
from gold_sales_fact
group by product_id
order by total_units_sold desc
limit 10;

select round(sum(freight_value),2) as revenue_by_freight   -- Total revenue generated by freight.
from gold_sales_fact;

select count(delivery_days) as delayed_deliveries         -- All delayed delivery count.
from gold_sales_fact
where delivery_days > (select avg(delivery_days) from gold_sales_fact);
